Use HTTPS for Maven repositories
This commit also ignores broken test due to the following exception:

java.sql.SQLException: Unable to load authentication plugin 'caching_sha2_password'.